name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files
        run: |
          ls -la
          find . -name pubspec.yaml

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: |
          cd $(dirname $(find . -name pubspec.yaml | head -1))
          flutter pub get

      - name: Build APK
        run: |
          cd $(dirname $(find . -name pubspec.yaml | head -1))
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: "**/app-release.apk"
